services:
  web:
    build: app
    ports:
      - "8000:5000"
    networks:
      - frontend
      - backend
    environment:
      - BASE_URL=http://localhost:5000
      - ENDPOINT_LLAMA3=http://ollama:11434/api/chat
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://user:password@db:3306/dbname
  # ollama:
  #   build: ollama
  #   ports:
  #     - "11434:11434"
  #   networks:
  #     - backend
  db:
    build: database
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./database/mysql:/var/lib/mysql
    networks:
      - backend
    ports:
      - "3307:3306"

networks:
  frontend:
    name: frontend
    driver: bridge
  backend:
    name: backend
    driver: bridge
